exports.Define = {
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
  CODE_RAKU:'raku',
}