exports.Define = {
  CODE_RAKU: "raku",
  CODE_CIT: "cit",
  CODE_GMY: "gmy",
  CODE_PIC: "pic",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
  CODE_RAKU: "raku",
};
