exports.Def = {
  DB_COL: {
    POINT: "point_summary",
    MISSION_QUE: "mission_que",
    MISSION_QUE_HIS: "mission_que_history",
  },
  STATUS: { DONE: "done", FAIL: "fail", RUN: "run", BEFO: "befo" },
  CODE: {
    MOBA: "moba",
    WIMA: "wima",
    UQMO: "uqmo",

    RAKU: "raku",
    DMY: "dmy",
    CIT: "cit",
    GMY: "gmy",
    PIC: "pic",
    CRI: "cri",
    ECN: "ecn",
    I2I: "i2i",
    PTO: "pto",
    MOP: "mop",
    PEX: "pex",
    CMS: "cms",
    GPO: "gpo",
    GEN: "gen",
    SUG: "sug",
    LFM: "lfm",
    PST: "pst",
    PIL: "pil",
    AME: "ame",
  },
  MISSION: {
    KANJI: "kanji",
    ANQ_HAPPY: "anq_happy",
    CHINJU: "chinju",
    URANAI: "uranai",
    POINT_MOLL: "point_moll",
    CHIRASHI: "chirashi",
    NEWS: "news",
    RESEARCH1: "research1",
    QUIZ_DAILY: "quiz_daily",
    EITANGO: "eitango",
    ANZAN: "anzan",
    NANYOUBI: "nanyoubi",
    CLICK: "click",
    CLICK_NEWS: "click_news",
    READ_DOG: "read_dog",
    READ_CAT: "read_cat",
    READ_THANK: "read_thank",
    READ_ICHI: "read_ichi",
    OTANO: "otano",
    QUIZ_KENTEI: "quiz_kentei",
    ANQ_SUG: "anq_sug",
    ANQ_PARK: "anq_park",

    ANQ_MANGA: "anq_manga",
    ANQ_COLUM: "anq_colum",
    ANQ_PHOTO: "anq_photo",
    ANQ_KENKOU: "anq_kenkou",
    ANQ_COOK: "anq_cook",
    ANQ_HIRAMEKI: "anq_hirameki",
    ANQ_ZUKAN: "anq_zukan",
    ANQ_IJIN: "anq_ijin",
    ANQ_JAPAN: "anq_japan",
    ANQ_SITE: "anq_site",

    ANQ_CRI: "anq_cri",
    ANQ_GEN: "anq_gen",
    GPO_ANQ: "gpo_anq",
    POINTQ: "pointq",

    CM: "cm", // 内部処理のダミー用
    CM_URANAI: "cm_uranai",
    CM_DOTTI: "cm_dotti",
    CM_KENTEI: "cm_kentei",
    CM_POCHI: "cm_pochi",

    CM_COLUM: "cm_colum",
    CM_PHOTO: "cm_photo",
    CM_SITE: "cm_site",
    CM_ZUKAN: "cm_zukan",
    CM_JAPAN: "cm_japan",
    CM_COOK: "cm_cook",

    MOP_RESEARCH: "mop_research",
  },
};
